/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : string,
  'title' : string,
  'inStock' : boolean,
  'isbn' : string,
  'publishYear' : bigint,
  'description' : string,
  'author' : string,
  'genre' : string,
  'rating' : number,
  'coverUrl' : string,
  'price' : number,
  'reviewCount' : bigint,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'title' : string,
  'bookId' : string,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Review {
  'createdAt' : Timestamp,
  'bookId' : string,
  'reviewerName' : string,
  'comment' : string,
  'rating' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addReview' : ActorMethod<[string, string, number, string], Result>,
  'addToWishlist' : ActorMethod<[string], Result>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getBookById' : ActorMethod<[string], [] | [Book]>,
  'getBooksByGenre' : ActorMethod<[string], Array<Book>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getReviews' : ActorMethod<[string], Array<Review>>,
  'getWishlist' : ActorMethod<[], Array<Book>>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'removeFromWishlist' : ActorMethod<[string], Result>,
  'searchBooks' : ActorMethod<[string], Array<Book>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];