/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Book = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'inStock' : IDL.Bool,
  'isbn' : IDL.Text,
  'publishYear' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'rating' : IDL.Float64,
  'coverUrl' : IDL.Text,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'title' : IDL.Text,
  'bookId' : IDL.Text,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Review = IDL.Record({
  'createdAt' : Timestamp,
  'bookId' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Result],
      [],
    ),
  'addToWishlist' : IDL.Func([IDL.Text], [Result], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBookById' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem)],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'removeFromWishlist' : IDL.Func([IDL.Text], [Result], []),
  'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Book = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'inStock' : IDL.Bool,
    'isbn' : IDL.Text,
    'publishYear' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'rating' : IDL.Float64,
    'coverUrl' : IDL.Text,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'title' : IDL.Text,
    'bookId' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Review = IDL.Record({
    'createdAt' : Timestamp,
    'bookId' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Float64,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Result],
        [],
      ),
    'addToWishlist' : IDL.Func([IDL.Text], [Result], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBookById' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem)],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'removeFromWishlist' : IDL.Func([IDL.Text], [Result], []),
    'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };